root:
  - path: \etc\mesosphere\setup-flags\repository-url
    permissions: "0644"
    owner: root
    content: |
      {{ bootstrap_url }}
  - path: \etc\mesosphere\setup-flags\cluster-package-list
    permissions: "0644"
    owner: root
    content: |
      {{ cluster_package_list_id }}
  - path: \etc\mesosphere\docker_credentials
    permissions: "0600"
    content: |
        {{ cluster_docker_credentials }}
